### ISSUE TITLE
Removing pad do a crash

### ISSUE THREAD

**Issue by bonnebulle** [ether/ep_adminpads2#83]
### synopsis
From the admin pad, on clic to remove a fresh new pad, serveur crash
error : 
```[WARN] console - padRemove padID context property is deprecated; use pad.id instead```
+
```
[ERROR] server - Error: ENOENT: no such file or directory, stat '/my/path/etherpad-lite/src/static/images/pad_folder_name'
```

#### context
Am using Etherpad Version number: 1.9.0 (not stable/safe, I know)
and a lot of plugins (making this all not very stable)
I use https://www.npmjs.com/package/ep_image_upload
(configured in local to create a folder when upload image content)

### conclusion
I need to search a way with ep_image_upload
Or there is quick way to fix it an other way ?

Thanks

**Comment by SamTV12345** [comment]
It's probably the plugin ep_image_upload that is causing this issue as it fails when removing an image.

**Comment by bonnebulle** [comment]
It look you are right ep_image_upload was not working well for me
